apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: 049417293525.dkr.ecr.eu-central-1.amazonaws.com/airflow:main-6a8835f2ecc18597bfc3c3fc2d51025d36da52d6
          name: guestbook-ui
          ports:
            - containerPort: 80