apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: 049417293525.dkr.ecr.eu-central-1.amazonaws.com/airflow:3c70c89ff7f99c121c41fb4f461262fda2e72f3b
          name: guestbook-ui
          ports:
            - containerPort: 80