apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: 049417293525.dkr.ecr.eu-central-1.amazonaws.com/airflow:version-eb65817add93600f13620324c0c729b513f4c197
          name: guestbook-ui
          ports:
            - containerPort: 80